### ISSUE TITLE
置灰网站致敬英雄

### ISSUE THREAD

**Issue by Jiang-Xuan** [Jiang-Xuan/tuchuang.space#156]
置灰网站

```css
body {
  filter: grayscale(1);
}
```
https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/grayscale

![image](https://user-images.githubusercontent.com/13357301/78362921-8195d280-75ed-11ea-8756-02f77d987f2b.png)

用 alert banner. 文案为 `致敬抗疫的英雄, 西昌救火英雄。 愿英魂长存。`

从 0.3.0 版本切出来, 发布版本 0.3.1
